### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by PabloLeon** [pistocop/subreddit-comments-dl#1]
Thanks for putting this together! I was getting UnicodeEncodeErrors (in line 99) of the dictlist_to_csv method. Adding encoding='utf-8' to the with open(file_path, 'w', newline='') as output_file (line 96) fixed that for me!

**Comment by PabloLeon** [comment]
And I also had to update the read/write methods in the builder

**Comment by pistocop** [comment]
Hi @PabloLeon,

Thanks for the interest, is always a joy to receive feedback from the community.

Good question, I have checked the `open` code on the [official documentation](https://docs.python.org/3/library/functions.html#open) that report:
> In text mode, if encoding is not specified the encoding used is platform dependent

So I agree with you that could be a better approach to specify the encoding instead of having an inconsistent run based on the platform.

I'm wondering if the encoding is enough for all kinds of usages (e.g. special characters, Latin, Chinese, etc.), but from [UTF-8 wiki](https://en.wikipedia.org/wiki/UTF-8) looks like it is the best approach to manage all type of characters.

I will release the new version with the UTF-8 encoding soon!
